import type { ScenarioDefinition, WhatIfModifier } from "./types";

/**
 * A compact, teachable interpretation of the Red Cliffs campaign. The dates,
 * coalition, disease pressure, chained fleet, and fire attack are historical
 * anchors; the numeric values are intentionally transparent simulation inputs.
 */
export const RED_CLIFFS_SCENARIO = {
  id: "red-cliffs-208",
  title: "Battle of Red Cliffs",
  subtitle: "A living simulation of alliance, logistics, weather, and strategy",
  era: "Late Han dynasty · 208 CE",
  historicalNote:
    "The scenario distinguishes its historical anchors from calculated outcomes. Exact numbers, individual dialogue, and counterfactual consequences are modeled inferences rather than established facts.",
  presentation: {
    scene: "red-cliffs",
    metricLabels: {
      morale: "Coalition morale",
      supplies: "Supply resilience",
      mobility: "River mobility",
      cohesion: "Alliance cohesion",
    },
    causalThread: {
      title: "Illness → readiness → fleet formation",
      description:
        "Disease risk is {diseaseRisk}/100. Watch how it influences decisions without making any one factor a complete explanation.",
    },
    mission: {
      title: "Trace the fragile alliance",
      description:
        "Identify how weather, health, and trust shape the coalition’s choices. Follow reports instead of assuming a leader knows everything.",
      steps: ["Council", "Camp report", "Test plan"],
    },
    whatIfPromptHint: "Try: What if supplies doubled?",
  },
  maxTicks: 8,
  locations: [
    {
      id: "xiakou",
      name: "Xiakou coalition camp",
      kind: "camp",
      position: { x: -7, y: 0, z: 3.9 },
      description: "The allied command camp where Sun Quan's and Liu Bei's forces coordinate.",
    },
    {
      id: "wulin",
      name: "Wulin fleet anchorage",
      kind: "harbor",
      position: { x: 6, y: 0, z: 1 },
      description: "Cao Cao's large northern fleet is anchored along the riverbank.",
    },
    {
      id: "chibi-river",
      name: "Red Cliffs river channel",
      kind: "river",
      position: { x: 0, y: 0, z: 0 },
      description: "A narrow Yangtze channel where wind, current, and fleet formation matter.",
    },
    {
      id: "jiangxia",
      name: "Jiangxia supply landing",
      kind: "harbor",
      position: { x: -4, y: 0, z: -4.5 },
      description: "A landing used for messages, provisions, and coalition reinforcements.",
    },
    {
      id: "wulin-road",
      name: "Wulin retreat road",
      kind: "road",
      position: { x: 8, y: 0, z: -4.5 },
      description: "A muddy route that becomes important if the northern army withdraws.",
    },
    {
      id: "river-village",
      name: "Riverside village",
      kind: "village",
      position: { x: -1, y: 0, z: 4.7 },
      description: "A civilian settlement affected by passing armies and requisitioned supplies.",
    },
  ],
  agents: [
    {
      id: "cao-cao",
      name: "Cao Cao",
      title: "Chancellor of Han",
      role: "ruler",
      factionId: "wei",
      biography: "A northern warlord seeking to extend his control south along the Yangtze.",
      personality: { traits: ["ambitious", "decisive", "pragmatic"], leadership: 91, caution: 44, adaptability: 80 },
      currentLocationId: "wulin",
      initialObjective: "Secure the river crossing and break the coalition before it consolidates.",
      emotionalState: { primary: "confident", intensity: 72 },
      inventory: ["campaign maps", "seal", "field dispatches"],
      trust: { "cao-ren": 82, "zhang-liao": 78 },
      initialKnowledge: [
        {
          id: "wei-fleet-scale",
          statement: "The northern force has a larger fleet but many personnel are unfamiliar with river warfare.",
          confidence: 92,
          learnedAtTick: 0,
          evidence: "historical-fact",
        },
      ],
      initialMemory: [
        {
          id: "cao-cao-southern-campaign",
          summary: "The rapid southern campaign has stretched supply and health systems.",
          tick: 0,
          importance: 87,
          kind: "shortage",
        },
      ],
    },
    {
      id: "sun-quan",
      name: "Sun Quan",
      title: "Lord of Jiangdong",
      role: "ruler",
      factionId: "sun-liu",
      biography: "Leader of Jiangdong whose decision to resist makes a coalition possible.",
      personality: { traits: ["measured", "resolute", "political"], leadership: 86, caution: 66, adaptability: 77 },
      currentLocationId: "xiakou",
      initialObjective: "Preserve Jiangdong's autonomy while holding the alliance together.",
      emotionalState: { primary: "wary", intensity: 58 },
      inventory: ["alliance letters", "river charts"],
      trust: { "zhou-yu": 91, "lu-su": 87, "liu-bei": 58 },
      initialKnowledge: [
        {
          id: "coalition-fragility",
          statement: "The alliance shares an immediate threat but has different long-term interests.",
          confidence: 89,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "sun-quan-council",
          summary: "The court debated submission and resistance before committing to oppose Cao Cao.",
          tick: 0,
          importance: 96,
          kind: "conversation",
        },
      ],
    },
    {
      id: "liu-bei",
      name: "Liu Bei",
      title: "Warlord of Xuande",
      role: "ruler",
      factionId: "sun-liu",
      biography: "A displaced leader whose surviving forces make the coalition broader but more complex.",
      personality: { traits: ["empathetic", "persistent", "diplomatic"], leadership: 82, caution: 62, adaptability: 83 },
      currentLocationId: "xiakou",
      initialObjective: "Keep his followers safe and contribute enough to sustain the coalition.",
      emotionalState: { primary: "resolute", intensity: 75 },
      inventory: ["refugee reports", "supply ledger"],
      trust: { "zhuge-liang": 95, "sun-quan": 62, "zhou-yu": 60 },
      initialKnowledge: [
        {
          id: "liu-bei-position",
          statement: "Liu Bei's forces need allied river expertise and reliable supplies.",
          confidence: 84,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "liu-bei-retreat",
          summary: "The retreat from Jing Province made civilian safety and food stores urgent concerns.",
          tick: 0,
          importance: 90,
          kind: "shortage",
        },
      ],
    },
    {
      id: "zhou-yu",
      name: "Zhou Yu",
      title: "Coalition commander",
      role: "commander",
      factionId: "sun-liu",
      biography: "The coalition commander responsible for turning local river knowledge into a defensive plan.",
      personality: { traits: ["composed", "analytical", "bold"], leadership: 90, caution: 58, adaptability: 88 },
      currentLocationId: "xiakou",
      initialObjective: "Use maneuver, weather, and local knowledge to offset Wei's numerical advantage.",
      emotionalState: { primary: "calm", intensity: 68 },
      inventory: ["fleet roster", "signal flags", "river current notes"],
      trust: { "sun-quan": 91, "huang-gai": 85, "zhuge-liang": 66 },
      initialKnowledge: [
        {
          id: "zhou-yu-river-advantage",
          statement: "Small, experienced river fleets can maneuver better than a larger unfamiliar formation.",
          confidence: 90,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "zhou-yu-inspection",
          summary: "Fleet inspections identified disease and seasickness among many northern troops.",
          tick: 0,
          importance: 92,
          kind: "observation",
        },
      ],
    },
    {
      id: "zhuge-liang",
      name: "Zhuge Liang",
      title: "Strategist",
      role: "strategist",
      factionId: "sun-liu",
      biography: "A strategist representing Liu Bei's forces and helping maintain coalition coordination.",
      personality: { traits: ["observant", "patient", "persuasive"], leadership: 79, caution: 73, adaptability: 93 },
      currentLocationId: "jiangxia",
      initialObjective: "Translate observations into plans the coalition can jointly support.",
      emotionalState: { primary: "calm", intensity: 70 },
      inventory: ["astronomical notes", "sealed messages"],
      trust: { "liu-bei": 95, "zhou-yu": 67, "lu-su": 76 },
      initialKnowledge: [
        {
          id: "zhuge-liang-weather",
          statement: "Wind direction could determine whether fire ships endanger the enemy or the coalition.",
          confidence: 81,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "zhuge-liang-alliance",
          summary: "Diplomatic work in Jiangdong showed that shared evidence is needed to sustain trust.",
          tick: 0,
          importance: 84,
          kind: "conversation",
        },
      ],
    },
    {
      id: "huang-gai",
      name: "Huang Gai",
      title: "Veteran naval officer",
      role: "officer",
      factionId: "sun-liu",
      biography: "A veteran officer associated in traditional accounts with the fire-ship plan.",
      personality: { traits: ["courageous", "direct", "disciplined"], leadership: 76, caution: 41, adaptability: 71 },
      currentLocationId: "xiakou",
      initialObjective: "Prepare a credible deception without exposing the coalition fleet too early.",
      emotionalState: { primary: "resolute", intensity: 86 },
      inventory: ["signal lamp", "oil jars", "decoy sails"],
      trust: { "zhou-yu": 85, "sun-quan": 72 },
      initialKnowledge: [
        {
          id: "huang-gai-fire-ships",
          statement: "Prepared fire ships require a favorable wind, timing, and a vulnerable enemy formation.",
          confidence: 93,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "huang-gai-training",
          summary: "The crews have rehearsed signals and emergency withdrawal routes.",
          tick: 0,
          importance: 73,
          kind: "discovery",
        },
      ],
    },
    {
      id: "lu-su",
      name: "Lu Su",
      title: "Diplomat and adviser",
      role: "diplomat",
      factionId: "sun-liu",
      biography: "An adviser whose relationships help bridge the interests of Sun Quan and Liu Bei.",
      personality: { traits: ["pragmatic", "patient", "inclusive"], leadership: 74, caution: 75, adaptability: 82 },
      currentLocationId: "xiakou",
      initialObjective: "Keep communication open between commanders, civilians, and supply workers.",
      emotionalState: { primary: "hopeful", intensity: 62 },
      inventory: ["dispatch book", "supply requests"],
      trust: { "sun-quan": 87, "liu-bei": 73, "zhuge-liang": 76 },
      initialKnowledge: [
        {
          id: "lu-su-coordination",
          statement: "Coalition cohesion depends on dependable reports rather than assumptions about allies.",
          confidence: 86,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "lu-su-negotiation",
          summary: "Previous negotiations made the alliance possible but did not erase competing priorities.",
          tick: 0,
          importance: 88,
          kind: "promise",
        },
      ],
    },
    {
      id: "river-messenger",
      name: "River Messenger",
      role: "messenger",
      factionId: "neutral",
      biography: "A composite civilian courier used to surface how information travels between camps and river settlements.",
      personality: { traits: ["attentive", "careful", "resourceful"], leadership: 40, caution: 81, adaptability: 85 },
      currentLocationId: "river-village",
      initialObjective: "Deliver accurate reports while keeping clear of military pressure on local communities.",
      emotionalState: { primary: "anxious", intensity: 55 },
      inventory: ["river skiff", "wax tablets"],
      trust: { "lu-su": 66, "zhou-yu": 48 },
      initialKnowledge: [
        {
          id: "messenger-civilian-impact",
          statement: "Large troop movements have increased local demand for food, boats, and shelter.",
          confidence: 78,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "messenger-river-observation",
          summary: "The river current is fast, and weather changes can delay small civilian craft.",
          tick: 0,
          importance: 69,
          kind: "observation",
        },
      ],
    },
  ],
  initialWorld: {
    day: 0,
    phase: "dawn",
    weather: {
      condition: "overcast",
      windDirection: "northwest",
      windStrength: 24,
      precipitation: 18,
      visibility: 74,
    },
    factions: {
      wei: {
        id: "wei",
        name: "Cao Cao's northern force",
        color: "#c85b47",
        strategicGoal: "Force a southern capitulation and control the Yangtze corridor.",
        resources: { food: 74, supplies: 69, morale: 64, readiness: 66, fleet: 88 },
      },
      "sun-liu": {
        id: "sun-liu",
        name: "Sun–Liu coalition",
        color: "#4da892",
        strategicGoal: "Preserve southern autonomy through coordinated river defense.",
        resources: { food: 57, supplies: 61, morale: 71, readiness: 76, fleet: 58 },
      },
      neutral: {
        id: "neutral",
        name: "River communities",
        color: "#c9a66b",
        strategicGoal: "Protect food stores, homes, and safe movement along the river.",
        resources: { food: 61, supplies: 46, morale: 53, readiness: 18, fleet: 22 },
      },
    },
    infrastructure: {
      "xiakou-landing": {
        id: "xiakou-landing",
        name: "Xiakou landing",
        status: "intact",
        capacity: 78,
        locationId: "xiakou",
      },
      "wulin-anchorage": {
        id: "wulin-anchorage",
        name: "Wulin anchorage",
        status: "strained",
        capacity: 84,
        locationId: "wulin",
      },
      "wulin-retreat-road": {
        id: "wulin-retreat-road",
        name: "Wulin retreat road",
        status: "intact",
        capacity: 66,
        locationId: "wulin-road",
      },
    },
    pressures: {
      diseaseRisk: 52,
      supplyStrain: 46,
      riverMobility: 67,
      diplomaticCohesion: 69,
      fireAttackEffectiveness: 0,
    },
  },
  timeline: [
    {
      id: "coalition-council",
      tick: 1,
      title: "Coalition council confirms resistance",
      description: "Sun Quan's and Liu Bei's representatives commit to coordination despite uneven resources and uncertain trust.",
      kind: "diplomacy",
      evidence: "historical-fact",
      locationId: "xiakou",
      participantIds: ["sun-quan", "liu-bei", "zhou-yu", "zhuge-liang", "lu-su"],
      messages: [
        {
          id: "sun-quan-council-message",
          speakerId: "sun-quan",
          recipientId: "zhou-yu",
          channel: "spoken",
          text: "We resist together. Keep the alliance informed before either force moves.",
          evidence: "historical-inference",
        },
        {
          id: "zhou-yu-council-reply",
          speakerId: "zhou-yu",
          recipientId: "sun-quan",
          channel: "spoken",
          text: "I will coordinate the river defense and protect our shared supply routes.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "At Xiakou, lantern light gathers the two camps around one table. The coalition chooses resistance, while the unease beneath its promises remains visible.",
        why: "A shared decision makes coordinated movement possible, but it does not erase competing priorities or unequal resources within the alliance.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-pressure", pressure: "diplomaticCohesion", amount: 12 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "morale", amount: 7 },
        {
          type: "set-agent-objective",
          agentId: "zhou-yu",
          objective: "Coordinate a river defense that protects coalition mobility and civilian supply routes.",
        },
      ],
    },
    {
      id: "northern-health-pressure",
      tick: 2,
      title: "Illness and supply pressure surface in the northern camp",
      description: "The campaign's speed, unfamiliar climate, and crowded vessels weaken readiness in Cao Cao's force.",
      kind: "logistics",
      evidence: "historical-fact",
      locationId: "wulin",
      participantIds: ["cao-cao", "river-messenger"],
      messages: [
        {
          id: "messenger-health-report",
          speakerId: "river-messenger",
          recipientId: "zhou-yu",
          channel: "dispatch",
          text: "Reports from the anchorage describe crowded vessels, illness, and slower preparation.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "Across the river at Wulin, cramped decks and a strange southern climate turn the northern camp quiet and slow. Before swords meet, sickness and supply strain begin narrowing Cao Cao's choices.",
        why: "Health and supply pressure reduce readiness before a battle begins, shaping which strategies commanders judge practical.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-pressure", pressure: "diseaseRisk", amount: 19 },
        { type: "adjust-pressure", pressure: "supplyStrain", amount: 11 },
        { type: "adjust-resource", factionId: "wei", resource: "readiness", amount: -12 },
        { type: "adjust-resource", factionId: "wei", resource: "morale", amount: -7 },
        {
          type: "share-knowledge",
          agentId: "zhou-yu",
          knowledge: {
            id: "zhou-yu-northern-health",
            statement: "Reports from the northern anchorage indicate that illness is reducing readiness.",
            confidence: 72,
            learnedAtTick: 2,
            sourceAgentId: "river-messenger",
            evidence: "historical-inference",
          },
          memory: {
            id: "zhou-yu-health-report",
            summary: "A river report links crowded northern vessels to declining readiness.",
            tick: 2,
            importance: 82,
            kind: "discovery",
          },
        },
      ],
    },
    {
      id: "fleet-chained",
      tick: 3,
      title: "Northern ships are linked for stability",
      description: "To reduce motion for troops unused to river travel, the northern fleet adopts a more fixed formation.",
      kind: "strategy",
      evidence: "historical-fact",
      locationId: "wulin",
      participantIds: ["cao-cao"],
      messages: [
        {
          id: "cao-cao-fleet-order",
          speakerId: "cao-cao",
          channel: "spoken",
          text: "Stabilize the formation. The troops need steadier ground beneath them.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "At the anchorage, ropes and timbers draw the northern ships into steadier lines. The remedy calms unsettled troops, but it leaves a whole fleet sharing the same danger.",
        why: "A response to seasickness can improve short-term stability while reducing the fleet's ability to maneuver or separate from danger.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-pressure", pressure: "riverMobility", amount: -18 },
        { type: "adjust-resource", factionId: "wei", resource: "readiness", amount: 4 },
        {
          type: "set-infrastructure",
          infrastructureId: "wulin-anchorage",
          status: "strained",
          capacity: 70,
        },
      ],
    },
    {
      id: "fire-ships-prepared",
      tick: 4,
      title: "Coalition prepares a fire-ship deception",
      description: "Huang Gai's crews ready decoy vessels, but the plan remains dependent on wind and timing.",
      kind: "strategy",
      evidence: "historical-inference",
      locationId: "xiakou",
      participantIds: ["zhou-yu", "huang-gai", "zhuge-liang"],
      messages: [
        {
          id: "huang-gai-preparation-message",
          speakerId: "huang-gai",
          recipientId: "zhou-yu",
          channel: "spoken",
          text: "The decoy crews are ready, but timing and wind will decide whether this plan can move.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "In the coalition camp, crews coat decoy vessels and rehearse signals under watchful silence. The plan is ready, but it waits for the river and wind to permit it.",
        why: "Preparation creates an option, not an outcome: it only becomes useful when geography, weather, and enemy formation align.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-pressure", pressure: "fireAttackEffectiveness", amount: 22 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "readiness", amount: 6 },
        {
          type: "set-agent-objective",
          agentId: "huang-gai",
          objective: "Wait for a safe wind window, then direct the decoy fire ships toward the linked fleet.",
        },
        {
          type: "move-agent",
          agentId: "huang-gai",
          locationId: "chibi-river",
          status: "occupied",
        },
      ],
    },
    {
      id: "southeast-wind",
      tick: 5,
      title: "A strong southeast wind opens a narrow opportunity",
      description: "A favorable wind turns the river channel into an opportunity for the coalition's fire-ship plan.",
      kind: "weather",
      evidence: "historical-inference",
      locationId: "chibi-river",
      participantIds: ["zhou-yu", "zhuge-liang", "huang-gai"],
      messages: [
        {
          id: "zhou-yu-wind-message",
          speakerId: "zhou-yu",
          recipientId: "huang-gai",
          channel: "signal",
          text: "The channel is opening. Keep the approach measured and watch the current.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "A southeast wind lifts across the channel and turns the current into an ally. The scene reconstructs a plausible opening from the campaign's weather and river constraints, rather than claiming every detail is certain.",
        why: "The wind affects direction of travel and fire risk, turning the river's geography from a constraint into an opportunity for one side.",
        whyEvidence: "historical-inference",
      },
      effects: [
        {
          type: "set-weather",
          weather: { condition: "clear", windDirection: "southeast", windStrength: 84, precipitation: 0, visibility: 88 },
        },
        { type: "adjust-pressure", pressure: "fireAttackEffectiveness", amount: 34 },
        {
          type: "share-knowledge",
          agentId: "huang-gai",
          knowledge: {
            id: "huang-gai-wind-window",
            statement: "The wind now favors a fire-ship approach toward the northern anchorage.",
            confidence: 88,
            learnedAtTick: 5,
            sourceAgentId: "zhou-yu",
            evidence: "historical-inference",
          },
        },
      ],
    },
    {
      id: "fire-attack",
      tick: 6,
      title: "Fire ships enter the channel",
      description: "The attack's modeled result depends on preparation, the linked fleet, and the wind actually present in this run.",
      kind: "battle",
      evidence: "historical-fact",
      locationId: "chibi-river",
      participantIds: ["zhou-yu", "huang-gai", "cao-cao"],
      worldAction: "fire-attack",
      narration: {
        story:
          "As dusk closes over Red Cliffs, Huang Gai's decoys move from plan into peril. What follows is not predetermined: linked ships, prepared crews, and the wind must converge.",
        why: "The modeled outcome depends on linked ships, preparation, and the actual wind present in this run; none of those factors acts alone.",
        whyEvidence: "historical-inference",
      },
      effects: [
        {
          type: "resolve-fire-attack",
          attackerFactionId: "sun-liu",
          defenderFactionId: "wei",
          baseImpact: 58,
          windThreshold: 55,
        },
      ],
    },
    {
      id: "northern-retreat",
      tick: 7,
      title: "Northern force begins to withdraw",
      description: "Losses, disrupted movement, and pressure on the anchorage make an organized withdrawal more likely.",
      kind: "retreat",
      evidence: "historical-fact",
      locationId: "wulin-road",
      participantIds: ["cao-cao", "river-messenger"],
      messages: [
        {
          id: "cao-cao-retreat-message",
          speakerId: "cao-cao",
          channel: "dispatch",
          text: "Preserve the people and supplies that can still move. The road must stay open.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "Along Wulin's muddy road, order gives way to withdrawal. Losses, exhausted soldiers, blocked movement, and thinning supplies push the northern force away from the river.",
        why: "Withdrawal is driven by more than a single clash: damaged movement, morale, supplies, and health all affect whether a force can remain in place.",
        whyEvidence: "historical-inference",
      },
      condition: { type: "pressure-at-least", pressure: "fireAttackEffectiveness", value: 50 },
      effects: [
        { type: "adjust-resource", factionId: "wei", resource: "morale", amount: -10 },
        { type: "adjust-resource", factionId: "wei", resource: "supplies", amount: -14 },
        { type: "adjust-pressure", pressure: "supplyStrain", amount: 16 },
        {
          type: "move-agent",
          agentId: "cao-cao",
          locationId: "wulin-road",
          status: "retreating",
        },
        {
          type: "set-agent-emotion",
          agentId: "cao-cao",
          emotion: { primary: "frustrated", intensity: 76 },
        },
      ],
    },
    {
      id: "civilian-aftermath",
      tick: 8,
      title: "River communities assess the aftermath",
      description: "The simulation closes by foregrounding disrupted food stores, damaged movement routes, and civilian uncertainty.",
      kind: "social",
      evidence: "historical-inference",
      locationId: "river-village",
      participantIds: ["river-messenger", "lu-su"],
      messages: [
        {
          id: "messenger-aftermath-message",
          speakerId: "river-messenger",
          recipientId: "lu-su",
          channel: "spoken",
          text: "Food stores and safe crossings are the first concerns for families near the river.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "After the commanders leave the frame, families on the river count grain, boats, and safe crossings. The campaign's final cost is measured in disrupted lives as much as damaged fleets.",
        why: "The consequences of a campaign extend beyond commanders: disrupted food, housing, and safe travel shape civilian decisions after the engagement.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-resource", factionId: "neutral", resource: "food", amount: -11 },
        { type: "adjust-resource", factionId: "neutral", resource: "morale", amount: -9 },
        { type: "adjust-pressure", pressure: "supplyStrain", amount: 8 },
        {
          type: "set-agent-objective",
          agentId: "lu-su",
          objective: "Document civilian needs and reopen safe supply routes after the engagement.",
        },
      ],
    },
  ],
} as const satisfies ScenarioDefinition;

export const RED_CLIFFS_WHAT_IF_PRESETS = [
  {
    id: "no-strong-winds",
    type: "weather",
    label: "No strong winds",
    description: "Keep the river wind weak and variable, removing the favorable fire-ship window.",
    source: "user",
    startsAtTick: 0,
    weather: { windDirection: "variable", windStrength: 16, visibility: 64 },
  },
  {
    id: "coalition-supplies-doubled",
    type: "resource",
    label: "Coalition supplies doubled",
    description: "Give the coalition a larger starting reserve of campaign supplies.",
    source: "user",
    startsAtTick: 0,
    factionId: "sun-liu",
    resource: "supplies",
    amount: 35,
  },
  {
    id: "wei-reinforcements-arrive",
    type: "reinforcement",
    label: "Wei reinforcements arrive early",
    description: "A rested contingent reaches Wulin before the fire-ship attack.",
    source: "user",
    factionId: "wei",
    readiness: 14,
    supplies: 12,
    morale: 8,
    arrivalTick: 4,
  },
] as const satisfies readonly WhatIfModifier[];
