import type { ScenarioDefinition, WhatIfModifier } from "./types";

/**
 * A compact, teachable interpretation of the Battle of Waterloo. The rain,
 * delayed French opening, fighting at the farms, Prussian arrival, and French
 * retreat are historical anchors. Resource values, dialogue, and every
 * counterfactual consequence are transparent simulation inferences.
 */
export const WATERLOO_SCENARIO = {
  id: "waterloo-1815",
  title: "Battle of Waterloo",
  subtitle: "A living simulation of rain, terrain, coalition timing, and command under uncertainty",
  era: "18 June 1815 · Belgium",
  historicalNote:
    "This scenario distinguishes documented events from modeled interpretation. The weather, broad sequence of the battle, and coalition movements are historical anchors; numerical resources, dialogue, and counterfactual outcomes are educational inferences.",
  presentation: {
    scene: "waterloo",
    metricLabels: {
      morale: "Coalition morale",
      supplies: "Ammunition resilience",
      mobility: "Ground mobility",
      cohesion: "Coalition coordination",
    },
    causalThread: {
      title: "Rain → ground → timing → coalition arrival",
      description:
        "Ground mobility is {groundMobility}/100. Watch how rain and roads affect artillery, timing, and the chance for allies to coordinate.",
    },
    mission: {
      title: "Trace the battle's timing problem",
      description:
        "Follow how mud, farm defenses, and the arrival of Prussian forces change the choices available on both sides.",
      steps: ["Read the ground", "Compare field reports", "Test coalition timing"],
    },
    whatIfPromptHint: "Try: What if the ground dried earlier?",
  },
  maxTicks: 8,
  locations: [
    {
      id: "la-belle-alliance",
      name: "La Belle Alliance command post",
      kind: "camp",
      position: { x: -7.4, y: 0, z: -2.8 },
      description: "A French command position south of the main ridge, close to the Charleroi road.",
    },
    {
      id: "french-artillery-line",
      name: "French artillery line",
      kind: "field",
      position: { x: -5.25, y: 0, z: -1.6 },
      description: "A modeled battery position between the French command post and the Allied ridge.",
    },
    {
      id: "hougoumont-approach",
      name: "Hougoumont approach",
      kind: "field",
      position: { x: -3, y: 0, z: 4.3 },
      description: "A covered approach used in the model to show forces moving toward the farm rather than appearing at its walls.",
    },
    {
      id: "french-cavalry-assembly",
      name: "French cavalry assembly",
      kind: "field",
      position: { x: -2.9, y: 0, z: 2 },
      description: "A modeled assembly area before cavalry attempts to pressure the Allied ridge.",
    },
    {
      id: "allied-square-line",
      name: "Allied square line",
      kind: "field",
      position: { x: 1.5, y: 0, z: 2.65 },
      description: "A modeled forward line where infantry formations resist cavalry pressure below the ridge.",
    },
    {
      id: "mont-saint-jean",
      name: "Mont-Saint-Jean ridge",
      kind: "camp",
      position: { x: 2.8, y: 0, z: 3.1 },
      description: "The Anglo-Allied defensive ridge north of the battlefield.",
    },
    {
      id: "hougoumont",
      name: "Hougoumont farm",
      kind: "fortress",
      position: { x: -0.7, y: 0, z: 5.5 },
      description: "A walled farm on the Allied right whose defense drew in repeated French attacks.",
    },
    {
      id: "la-haye-sainte",
      name: "La Haye Sainte farm",
      kind: "fortress",
      position: { x: 1.2, y: 0, z: 0.2 },
      description: "A fortified farm near the center of the Allied line and a focal point of the fighting.",
    },
    {
      id: "plancenoit",
      name: "Plancenoit",
      kind: "village",
      position: { x: 7.1, y: 0, z: -2.7 },
      description: "A village east of the main field where French and Prussian forces struggled for control.",
    },
    {
      id: "prussian-east-approach",
      name: "Prussian eastern approach",
      kind: "road",
      position: { x: 12.6, y: 0, z: -3.1 },
      description: "A modeled eastern route showing Prussian forces entering the field before reaching Plancenoit.",
    },
    {
      id: "imperial-guard-staging",
      name: "French reserve staging area",
      kind: "field",
      position: { x: -2.6, y: 0, z: 1.8 },
      description: "A modeled French reserve position before the late assault on the ridge.",
    },
    {
      id: "charleroi-withdrawal-road",
      name: "Charleroi withdrawal road",
      kind: "road",
      position: { x: -12.8, y: 0, z: -5.5 },
      description: "A modeled route south from the field used to show the French withdrawal.",
    },
    {
      id: "brussels-road",
      name: "Brussels road",
      kind: "road",
      position: { x: 6.7, y: 0, z: 4.9 },
      description: "The road behind the Allied ridge, important for communications, reserves, and withdrawal routes.",
    },
    {
      id: "waterloo-village",
      name: "Waterloo village",
      kind: "village",
      position: { x: 8.7, y: 0, z: 6.9 },
      description: "A civilian settlement beyond the battlefield, affected by troop movements and the aftermath.",
    },
  ],
  agents: [
    {
      id: "napoleon",
      name: "Napoleon Bonaparte",
      title: "Emperor of the French",
      role: "ruler",
      factionId: "wei",
      biography: "Commander of the French Army of the North, seeking to defeat the coalition armies before they could fully combine.",
      personality: { traits: ["decisive", "analytical", "ambitious"], leadership: 94, caution: 45, adaptability: 82 },
      currentLocationId: "la-belle-alliance",
      initialObjective: "Break the Allied line before Prussian forces can decisively reinforce it.",
      emotionalState: { primary: "confident", intensity: 72 },
      inventory: ["field maps", "dispatches", "spyglass"],
      trust: { ney: 70, "d-erlon": 73 },
      initialKnowledge: [
        {
          id: "napoleon-ground-condition",
          statement: "The rain-soaked ground makes artillery movement and cavalry action more difficult than on dry terrain.",
          confidence: 91,
          learnedAtTick: 0,
          evidence: "historical-fact",
        },
      ],
      initialMemory: [
        {
          id: "napoleon-campaign-timing",
          summary: "The campaign depends on separating coalition armies before their coordination becomes decisive.",
          tick: 0,
          importance: 96,
          kind: "battle",
        },
      ],
    },
    {
      id: "ney",
      name: "Michel Ney",
      title: "Marshal of France",
      role: "commander",
      factionId: "wei",
      biography: "A senior French commander directing attacks against the Allied position during the battle.",
      personality: { traits: ["brave", "forceful", "impulsive"], leadership: 88, caution: 31, adaptability: 66 },
      currentLocationId: "la-belle-alliance",
      initialObjective: "Find and exploit a break in the Allied center without exhausting the reserve.",
      emotionalState: { primary: "resolute", intensity: 84 },
      inventory: ["field orders", "telescope", "signal flags"],
      trust: { napoleon: 76, "d-erlon": 63 },
      initialKnowledge: [
        {
          id: "ney-allied-ridge",
          statement: "Much of the Allied force is sheltered behind the ridge, limiting what French observers can see clearly.",
          confidence: 79,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "ney-quatre-bras",
          summary: "Recent fighting has shown that each delay can give coalition forces more time to coordinate.",
          tick: 0,
          importance: 81,
          kind: "battle",
        },
      ],
    },
    {
      id: "d-erlon",
      name: "Jean-Baptiste Drouet, Comte d'Erlon",
      title: "I Corps commander",
      role: "officer",
      factionId: "wei",
      biography: "Commander of French I Corps, whose infantry was committed against the Allied center-left.",
      personality: { traits: ["methodical", "dutiful", "cautious"], leadership: 77, caution: 69, adaptability: 64 },
      currentLocationId: "la-belle-alliance",
      initialObjective: "Keep I Corps organized through muddy ground and prepare a coordinated attack on the ridge.",
      emotionalState: { primary: "wary", intensity: 61 },
      inventory: ["corps roster", "route sketches", "courier notes"],
      trust: { napoleon: 75, ney: 58 },
      initialKnowledge: [
        {
          id: "d-erlon-mud-report",
          statement: "The soft ground slows guns, ammunition wagons, and the pace of formed infantry.",
          confidence: 87,
          learnedAtTick: 0,
          evidence: "historical-fact",
        },
      ],
      initialMemory: [
        {
          id: "d-erlon-march-memory",
          summary: "Long marches and changing orders have left parts of the corps tired before the main battle begins.",
          tick: 0,
          importance: 72,
          kind: "shortage",
        },
      ],
    },
    {
      id: "wellington",
      name: "Arthur Wellesley",
      title: "Duke of Wellington",
      role: "commander",
      factionId: "sun-liu",
      biography: "Commander of the Anglo-Allied army, holding a defensive ridge while expecting Prussian support.",
      personality: { traits: ["composed", "pragmatic", "resolute"], leadership: 92, caution: 71, adaptability: 79 },
      currentLocationId: "mont-saint-jean",
      initialObjective: "Hold the ridge long enough for coordinated coalition support to arrive.",
      emotionalState: { primary: "resolute", intensity: 78 },
      inventory: ["ridge map", "dispatch book", "field glass"],
      trust: { blucher: 85, uxbridge: 77, baring: 69 },
      initialKnowledge: [
        {
          id: "wellington-defensive-position",
          statement: "The reverse slope gives parts of the Allied line shelter, but the farms and ridge must be held under sustained pressure.",
          confidence: 90,
          learnedAtTick: 0,
          evidence: "historical-fact",
        },
      ],
      initialMemory: [
        {
          id: "wellington-prussian-promise",
          summary: "Prussian support has been promised, but its exact arrival depends on roads, fighting, and communication.",
          tick: 0,
          importance: 95,
          kind: "promise",
        },
      ],
    },
    {
      id: "blucher",
      name: "Gebhard Leberecht von Blücher",
      title: "Prussian field marshal",
      role: "commander",
      factionId: "sun-liu",
      biography: "Commander of the Prussian army, moving toward the battlefield after earlier fighting at Ligny.",
      personality: { traits: ["determined", "direct", "loyal"], leadership: 90, caution: 47, adaptability: 74 },
      currentLocationId: "prussian-east-approach",
      initialObjective: "Bring Prussian forces into the battle and maintain contact with the Allied line.",
      emotionalState: { primary: "resolute", intensity: 88 },
      inventory: ["march orders", "liaison dispatches", "field map"],
      trust: { wellington: 85, uxbridge: 41 },
      initialKnowledge: [
        {
          id: "blucher-march-constraint",
          statement: "Mud, damaged roads, and distance can delay the arrival of the Prussian columns.",
          confidence: 88,
          learnedAtTick: 0,
          evidence: "historical-fact",
        },
      ],
      initialMemory: [
        {
          id: "blucher-ligny-memory",
          summary: "The Prussian army has recently fought at Ligny and must regroup while continuing its march westward.",
          tick: 0,
          importance: 91,
          kind: "battle",
        },
      ],
    },
    {
      id: "uxbridge",
      name: "Henry Paget",
      title: "Earl of Uxbridge",
      role: "officer",
      factionId: "sun-liu",
      biography: "Commander of the Anglo-Allied cavalry, responsible for moving reserves across a crowded and wet battlefield.",
      personality: { traits: ["alert", "disciplined", "bold"], leadership: 83, caution: 55, adaptability: 76 },
      currentLocationId: "mont-saint-jean",
      initialObjective: "Protect the ridge and preserve cavalry reserves for moments where movement can matter.",
      emotionalState: { primary: "calm", intensity: 67 },
      inventory: ["cavalry roster", "signal horn", "riding orders"],
      trust: { wellington: 79, blucher: 38 },
      initialKnowledge: [
        {
          id: "uxbridge-square-observation",
          statement: "Infantry squares can resist cavalry, but only if formations keep discipline under pressure.",
          confidence: 84,
          learnedAtTick: 0,
          evidence: "historical-fact",
        },
      ],
      initialMemory: [
        {
          id: "uxbridge-ridge-inspection",
          summary: "Wet ground and broken sightlines make it difficult to move and observe every part of the defensive line at once.",
          tick: 0,
          importance: 76,
          kind: "observation",
        },
      ],
    },
    {
      id: "baring",
      name: "Georg Baring",
      title: "La Haye Sainte defender",
      role: "soldier",
      factionId: "sun-liu",
      biography: "A King's German Legion officer commanding defenders at La Haye Sainte during the battle.",
      personality: { traits: ["steadfast", "observant", "protective"], leadership: 68, caution: 63, adaptability: 72 },
      currentLocationId: "la-haye-sainte",
      initialObjective: "Hold the farm as long as ammunition and the surviving defenders allow.",
      emotionalState: { primary: "wary", intensity: 74 },
      inventory: ["ammunition tally", "farm keys", "signal cloth"],
      trust: { wellington: 68, uxbridge: 48 },
      initialKnowledge: [
        {
          id: "baring-ammunition-limit",
          statement: "The farm's defense depends on a limited ammunition supply and on relief reaching the position in time.",
          confidence: 92,
          learnedAtTick: 0,
          evidence: "historical-fact",
        },
      ],
      initialMemory: [
        {
          id: "baring-farm-preparation",
          summary: "The defenders have prepared the farm's openings and know that an isolated position cannot be held indefinitely.",
          tick: 0,
          importance: 85,
          kind: "observation",
        },
      ],
    },
    {
      id: "french-assault-column",
      name: "French assault column",
      title: "Modeled French formation",
      role: "soldier",
      renderKind: "unit",
      factionId: "wei",
      biography: "A composite formation used to make the movement of a French column legible without claiming to represent every regiment on the field.",
      personality: { traits: ["disciplined", "fatigued", "responsive"], leadership: 54, caution: 48, adaptability: 58 },
      currentLocationId: "la-belle-alliance",
      initialObjective: "Move only when orders and ground conditions make an advance possible.",
      emotionalState: { primary: "resolute", intensity: 69 },
      inventory: ["muskets", "ammunition packs", "unit standard"],
      trust: { napoleon: 64, ney: 62, "d-erlon": 71 },
      initialKnowledge: [
        {
          id: "french-column-mud",
          statement: "The ground is slow and uneven; the column cannot arrive at the ridge with the same order it had at the command post.",
          confidence: 78,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "french-column-order",
          summary: "The formation waits for orders near La Belle Alliance while artillery and roads are assessed.",
          tick: 0,
          importance: 71,
          kind: "conversation",
        },
      ],
    },
    {
      id: "prussian-vanguard",
      name: "Prussian vanguard",
      title: "Modeled advance formation",
      role: "soldier",
      renderKind: "unit",
      factionId: "sun-liu",
      biography: "A composite advance formation used to show the Prussian approach, fighting at Plancenoit, and later pressure toward the ridge.",
      personality: { traits: ["determined", "orderly", "enduring"], leadership: 58, caution: 51, adaptability: 67 },
      currentLocationId: "prussian-east-approach",
      initialObjective: "Reach Plancenoit, maintain contact with the coalition, and keep moving despite mud and resistance.",
      emotionalState: { primary: "resolute", intensity: 76 },
      inventory: ["muskets", "march orders", "unit standard"],
      trust: { blucher: 82, wellington: 58 },
      initialKnowledge: [
        {
          id: "prussian-vanguard-route",
          statement: "The eastern approach is passable but slow, and the vanguard must fight before it can assist the main Allied line.",
          confidence: 80,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "prussian-vanguard-march",
          summary: "The formation has been moving toward the battlefield on muddy roads after earlier fighting.",
          tick: 0,
          importance: 82,
          kind: "battle",
        },
      ],
    },
    {
      id: "field-courier",
      name: "Field Courier",
      title: "Civilian messenger",
      role: "messenger",
      factionId: "neutral",
      biography: "A composite local courier used to show how reports, road conditions, and civilian concerns travel around the battlefield.",
      personality: { traits: ["careful", "resourceful", "empathetic"], leadership: 42, caution: 86, adaptability: 82 },
      currentLocationId: "waterloo-village",
      initialObjective: "Carry reliable reports while avoiding dangerous roads and protecting local families' needs.",
      emotionalState: { primary: "anxious", intensity: 58 },
      inventory: ["sealed notes", "road sketch", "water flask"],
      trust: { wellington: 43, blucher: 32, baring: 46 },
      initialKnowledge: [
        {
          id: "courier-civilian-pressure",
          statement: "Troop movements have made roads, shelter, food, and safe family travel increasingly uncertain for local people.",
          confidence: 77,
          learnedAtTick: 0,
          evidence: "historical-inference",
        },
      ],
      initialMemory: [
        {
          id: "courier-rain-memory",
          summary: "Heavy rain has turned local tracks muddy and has slowed ordinary travel between farms and villages.",
          tick: 0,
          importance: 74,
          kind: "observation",
        },
      ],
    },
  ],
  initialWorld: {
    day: 0,
    phase: "dawn",
    weather: {
      condition: "rain",
      windDirection: "southwest",
      windStrength: 17,
      precipitation: 76,
      visibility: 58,
    },
    factions: {
      wei: {
        id: "wei",
        name: "French Army",
        color: "#b84d44",
        strategicGoal: "Defeat the coalition before its armies can combine their strength on the field.",
        resources: { food: 73, supplies: 70, morale: 75, readiness: 72, fleet: 10 },
      },
      "sun-liu": {
        id: "sun-liu",
        name: "Allied and Prussian coalition",
        color: "#416eaa",
        strategicGoal: "Hold the defensive ridge and bring the coalition's separate forces into mutual support.",
        resources: { food: 69, supplies: 67, morale: 71, readiness: 70, fleet: 8 },
      },
      neutral: {
        id: "neutral",
        name: "Local communities and field services",
        color: "#b38b55",
        strategicGoal: "Protect access to shelter, food, medical aid, and safe movement around the battlefield.",
        resources: { food: 62, supplies: 48, morale: 55, readiness: 22, fleet: 3 },
      },
    },
    infrastructure: {
      "charleroi-road": {
        id: "charleroi-road",
        name: "Charleroi approach road",
        status: "strained",
        capacity: 52,
        locationId: "la-belle-alliance",
      },
      "brussels-road-route": {
        id: "brussels-road-route",
        name: "Brussels road route",
        status: "strained",
        capacity: 58,
        locationId: "brussels-road",
      },
      "hougoumont-gate": {
        id: "hougoumont-gate",
        name: "Hougoumont farm gate",
        status: "intact",
        capacity: 63,
        locationId: "hougoumont",
      },
      "la-haye-sainte-farm": {
        id: "la-haye-sainte-farm",
        name: "La Haye Sainte defenses",
        status: "intact",
        capacity: 59,
        locationId: "la-haye-sainte",
      },
    },
    pressures: {
      diseaseRisk: 21,
      supplyStrain: 49,
      riverMobility: 34,
      diplomaticCohesion: 78,
      fireAttackEffectiveness: 0,
    },
  },
  timeline: [
    {
      id: "overnight-rain",
      tick: 1,
      title: "Overnight rain turns the field to mud",
      description: "Heavy rain leaves roads and fields saturated before the battle's main fighting begins.",
      kind: "weather",
      evidence: "historical-fact",
      locationId: "la-belle-alliance",
      participantIds: ["napoleon", "d-erlon", "field-courier"],
      worldAction: "rain-field",
      messages: [
        {
          id: "courier-rain-report",
          speakerId: "field-courier",
          recipientId: "wellington",
          channel: "dispatch",
          text: "The tracks are deep with mud. Carts and riders are taking longer to reach the ridge.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "Rain lashes the fields through the night. By dawn, each wheel and boot must pull free of the mud, turning ordinary movement into a costly decision.",
        why: "Wet ground slows guns, wagons, and cavalry, so weather changes what commanders can move, when they can move it, and how much force arrives intact.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "set-weather", weather: { condition: "rain", precipitation: 82, visibility: 54 } },
        { type: "adjust-pressure", pressure: "supplyStrain", amount: 12 },
        { type: "adjust-pressure", pressure: "riverMobility", amount: -16 },
        { type: "adjust-resource", factionId: "wei", resource: "readiness", amount: -4 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "supplies", amount: -3 },
        { type: "move-agent", agentId: "field-courier", locationId: "brussels-road", status: "traveling" },
      ],
    },
    {
      id: "french-opening-delayed",
      tick: 2,
      title: "The French opening waits for firmer ground",
      description: "Napoleon delays the main attack while the soaked soil makes artillery and cavalry movement less reliable.",
      kind: "strategy",
      evidence: "historical-fact",
      locationId: "la-belle-alliance",
      participantIds: ["napoleon", "ney", "d-erlon"],
      worldAction: "artillery-barrage",
      messages: [
        {
          id: "napoleon-ground-order",
          speakerId: "napoleon",
          recipientId: "d-erlon",
          channel: "spoken",
          text: "Keep the guns and columns ready. We must not waste their strength in ground that will not carry them.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "South of the ridge, French batteries wait as the rain eases. Time passes, but the coalition's distant columns keep moving toward the sound of the guns.",
        why: "A delay can improve local movement conditions while also giving distant allies more time to coordinate, making timing a strategic trade-off rather than a simple pause.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "set-weather", weather: { condition: "overcast", precipitation: 47, visibility: 65 } },
        { type: "adjust-resource", factionId: "wei", resource: "supplies", amount: -4 },
        { type: "adjust-resource", factionId: "wei", resource: "readiness", amount: -3 },
        { type: "adjust-pressure", pressure: "diplomaticCohesion", amount: 4 },
        { type: "move-agent", agentId: "napoleon", locationId: "french-artillery-line", status: "occupied" },
        { type: "move-agent", agentId: "d-erlon", locationId: "french-artillery-line", status: "traveling" },
        { type: "move-agent", agentId: "ney", locationId: "french-cavalry-assembly", status: "traveling" },
        { type: "move-agent", agentId: "french-assault-column", locationId: "french-artillery-line", status: "traveling" },
        {
          type: "set-agent-objective",
          agentId: "d-erlon",
          objective: "Keep I Corps ready for an attack once the ground and orders permit movement.",
        },
      ],
    },
    {
      id: "hougoumont-holds",
      tick: 3,
      title: "Hougoumont absorbs repeated attacks",
      description: "Fighting at the walled farm intensifies as the French attempt to dislodge defenders on the Allied right.",
      kind: "battle",
      evidence: "historical-fact",
      locationId: "hougoumont",
      participantIds: ["ney", "wellington", "uxbridge", "field-courier"],
      worldAction: "farm-assault",
      messages: [
        {
          id: "wellington-hougoumont-report",
          speakerId: "field-courier",
          recipientId: "wellington",
          channel: "dispatch",
          text: "The farm is still holding, but the fighting is drawing men and ammunition toward its walls.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "At Hougoumont, smoke clings to the walls and orchards. A farm becomes a hinge in the battle, consuming attention, ammunition, and time far beyond its size on a map.",
        why: "Strongpoints can channel attacks into costly local fights. Holding one position may protect a wider line, but it also ties up people and supplies that cannot help elsewhere.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-resource", factionId: "wei", resource: "supplies", amount: -7 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "morale", amount: 5 },
        { type: "set-infrastructure", infrastructureId: "hougoumont-gate", status: "strained", capacity: 42 },
        { type: "move-agent", agentId: "ney", locationId: "hougoumont-approach", status: "traveling" },
        { type: "move-agent", agentId: "french-assault-column", locationId: "hougoumont-approach", status: "traveling" },
        {
          type: "share-knowledge",
          agentId: "wellington",
          knowledge: {
            id: "wellington-hougoumont-pressure",
            statement: "Hougoumont is holding, but repeated attacks are concentrating French and Allied resources around the farm.",
            confidence: 74,
            learnedAtTick: 3,
            sourceAgentId: "field-courier",
            evidence: "historical-inference",
          },
          memory: {
            id: "wellington-hougoumont-report",
            summary: "A courier reports that Hougoumont remains defended but is drawing in resources from both sides.",
            tick: 3,
            importance: 83,
            kind: "discovery",
          },
        },
      ],
    },
    {
      id: "cavalry-charges-meet-squares",
      tick: 4,
      title: "French cavalry meets Allied infantry squares",
      description: "Repeated cavalry attacks press the ridge, but disciplined infantry formations resist where they can maintain cohesion.",
      kind: "battle",
      evidence: "historical-fact",
      locationId: "mont-saint-jean",
      participantIds: ["ney", "wellington", "uxbridge"],
      worldAction: "cavalry-charge",
      messages: [
        {
          id: "uxbridge-square-message",
          speakerId: "uxbridge",
          recipientId: "wellington",
          channel: "spoken",
          text: "The squares are holding for now, but every charge drains the men and scatters our view of the field.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "Across the ridge, cavalry closes through smoke and rain-softened ground. Infantry tightens into squares, and the battle becomes a test of formation, endurance, and clear command amid confusion.",
        why: "Cavalry is most effective when it can exploit disorder. Cohesive infantry formations and uneven ground limit that opportunity, even while defenders pay a heavy price in fatigue and ammunition.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-resource", factionId: "wei", resource: "readiness", amount: -9 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "readiness", amount: -6 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "supplies", amount: -6 },
        { type: "adjust-pressure", pressure: "supplyStrain", amount: 8 },
        { type: "move-agent", agentId: "ney", locationId: "french-cavalry-assembly", status: "occupied" },
        { type: "move-agent", agentId: "french-assault-column", locationId: "allied-square-line", status: "traveling" },
        { type: "move-agent", agentId: "uxbridge", locationId: "allied-square-line", status: "occupied" },
        {
          type: "set-agent-emotion",
          agentId: "ney",
          emotion: { primary: "frustrated", intensity: 77 },
        },
      ],
    },
    {
      id: "prussian-vanguard-arrives",
      tick: 5,
      title: "Prussian vanguard reaches the eastern field",
      description: "Prussian forces arrive near Plancenoit, widening the battle and increasing pressure on the French right.",
      kind: "strategy",
      evidence: "historical-fact",
      locationId: "plancenoit",
      participantIds: ["blucher", "wellington", "napoleon", "field-courier"],
      worldAction: "reinforcement-arrival",
      messages: [
        {
          id: "blucher-arrival-message",
          speakerId: "blucher",
          recipientId: "wellington",
          channel: "dispatch",
          text: "Our leading troops are entering the eastern field. We will press toward Plancenoit and keep moving toward your line.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "Late in the day, Prussian columns appear through the eastern villages. Their arrival does not end the fighting; it changes the shape of the problem, forcing the French to look in two directions at once.",
        why: "Reinforcements matter not only by adding numbers. Their arrival can split an opponent's attention, alter routes, and make every remaining reserve more consequential.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-resource", factionId: "sun-liu", resource: "readiness", amount: 13 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "morale", amount: 9 },
        { type: "adjust-resource", factionId: "wei", resource: "readiness", amount: -5 },
        { type: "adjust-pressure", pressure: "diplomaticCohesion", amount: 8 },
        {
          type: "move-agent",
          agentId: "blucher",
          locationId: "plancenoit",
          status: "occupied",
        },
        {
          type: "move-agent",
          agentId: "prussian-vanguard",
          locationId: "plancenoit",
          status: "traveling",
        },
        {
          type: "move-agent",
          agentId: "napoleon",
          locationId: "la-belle-alliance",
          status: "occupied",
        },
        {
          type: "share-knowledge",
          agentId: "wellington",
          knowledge: {
            id: "wellington-prussian-arrival",
            statement: "Prussian leading troops have reached the eastern field and are engaging around Plancenoit.",
            confidence: 86,
            learnedAtTick: 5,
            sourceAgentId: "blucher",
            evidence: "historical-fact",
          },
          memory: {
            id: "wellington-prussian-dispatch",
            summary: "A dispatch confirms that Prussian troops have reached the eastern side of the battlefield.",
            tick: 5,
            importance: 96,
            kind: "conversation",
          },
        },
      ],
    },
    {
      id: "la-haye-sainte-captured",
      tick: 6,
      title: "La Haye Sainte is captured",
      description: "French troops take the farm after a prolonged defense, exposing the Allied center to closer pressure.",
      kind: "battle",
      evidence: "historical-fact",
      locationId: "la-haye-sainte",
      participantIds: ["baring", "ney", "wellington"],
      worldAction: "farm-assault",
      messages: [
        {
          id: "baring-withdrawal-message",
          speakerId: "baring",
          recipientId: "wellington",
          channel: "dispatch",
          text: "Our ammunition is spent. The surviving defenders are falling back toward the ridge.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "At La Haye Sainte, the defenders finally run out of what they need to keep every opening covered. The loss sharpens the pressure on the ridge just as the larger field is widening.",
        why: "A position can be tactically important because it changes distance and cover near a wider line. Its loss raises pressure on nearby defenders, but it does not by itself decide the campaign.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "set-infrastructure", infrastructureId: "la-haye-sainte-farm", status: "damaged", capacity: 24 },
        { type: "adjust-resource", factionId: "wei", resource: "morale", amount: 8 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "morale", amount: -8 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "supplies", amount: -8 },
        { type: "move-agent", agentId: "ney", locationId: "la-haye-sainte", status: "occupied" },
        { type: "move-agent", agentId: "french-assault-column", locationId: "la-haye-sainte", status: "occupied" },
        {
          type: "move-agent",
          agentId: "baring",
          locationId: "mont-saint-jean",
          status: "retreating",
        },
        {
          type: "set-agent-emotion",
          agentId: "baring",
          emotion: { primary: "fatigued", intensity: 89 },
        },
      ],
    },
    {
      id: "imperial-guard-repulse",
      tick: 7,
      title: "The Imperial Guard is repulsed",
      description: "A final French assault against the ridge is pushed back as Allied and Prussian pressure converges.",
      kind: "battle",
      evidence: "historical-fact",
      locationId: "mont-saint-jean",
      participantIds: ["napoleon", "ney", "wellington", "blucher", "uxbridge"],
      worldAction: "final-assault",
      messages: [
        {
          id: "wellington-guard-message",
          speakerId: "wellington",
          recipientId: "uxbridge",
          channel: "spoken",
          text: "The line is still here. Keep the formations together and make the pressure count.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "As evening closes in, the final French assault meets a line that has survived long enough to be joined by its allies. The failure spreads through a field already strained by mud, casualties, and divided attention.",
        why: "A late attack is shaped by everything that came before it: spent supplies, fatigued formations, terrain, surviving defenses, and whether allies arrive in time to share the burden.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-resource", factionId: "wei", resource: "morale", amount: -22 },
        { type: "adjust-resource", factionId: "wei", resource: "readiness", amount: -14 },
        { type: "adjust-resource", factionId: "sun-liu", resource: "morale", amount: 12 },
        { type: "adjust-pressure", pressure: "supplyStrain", amount: 7 },
        { type: "move-agent", agentId: "napoleon", locationId: "imperial-guard-staging", status: "occupied" },
        { type: "move-agent", agentId: "d-erlon", locationId: "imperial-guard-staging", status: "occupied" },
        { type: "move-agent", agentId: "french-assault-column", locationId: "mont-saint-jean", status: "traveling" },
        { type: "move-agent", agentId: "blucher", locationId: "mont-saint-jean", status: "traveling" },
        { type: "move-agent", agentId: "prussian-vanguard", locationId: "mont-saint-jean", status: "traveling" },
        { type: "move-agent", agentId: "uxbridge", locationId: "mont-saint-jean", status: "occupied" },
        {
          type: "set-agent-emotion",
          agentId: "napoleon",
          emotion: { primary: "frustrated", intensity: 86 },
        },
      ],
    },
    {
      id: "withdrawal-and-aftermath",
      tick: 8,
      title: "The French withdraw as civilians assess the aftermath",
      description: "The French retreat from the field while local people face damaged roads, disrupted shelter, and uncertainty after the battle.",
      kind: "retreat",
      evidence: "historical-inference",
      locationId: "waterloo-village",
      participantIds: ["napoleon", "field-courier", "wellington"],
      worldAction: "withdrawal",
      messages: [
        {
          id: "courier-aftermath-message",
          speakerId: "field-courier",
          recipientId: "wellington",
          channel: "spoken",
          text: "Families are looking for safe roads, water, and places to shelter. The field has not become safe just because the fighting moves away.",
          evidence: "historical-inference",
        },
      ],
      narration: {
        story:
          "The battle recedes down the road, but it does not disappear for the people living beside it. Homes, tracks, food stores, and care for the injured remain part of the historical story after the commanders leave the field.",
        why: "Battlefield outcomes reshape civilian life through damaged routes, lost supplies, displacement, and the need for medical care; these effects are modeled here as a perspective often absent from command histories.",
        whyEvidence: "historical-inference",
      },
      effects: [
        { type: "adjust-resource", factionId: "wei", resource: "supplies", amount: -13 },
        { type: "adjust-resource", factionId: "neutral", resource: "food", amount: -12 },
        { type: "adjust-resource", factionId: "neutral", resource: "morale", amount: -11 },
        { type: "adjust-pressure", pressure: "supplyStrain", amount: 11 },
        { type: "set-infrastructure", infrastructureId: "brussels-road-route", status: "damaged", capacity: 38 },
        {
          type: "move-agent",
          agentId: "napoleon",
          locationId: "charleroi-withdrawal-road",
          status: "retreating",
        },
        { type: "move-agent", agentId: "ney", locationId: "charleroi-withdrawal-road", status: "retreating" },
        { type: "move-agent", agentId: "d-erlon", locationId: "charleroi-withdrawal-road", status: "retreating" },
        { type: "move-agent", agentId: "french-assault-column", locationId: "charleroi-withdrawal-road", status: "retreating" },
        {
          type: "set-agent-objective",
          agentId: "field-courier",
          objective: "Help identify safe roads, shelter, and urgent needs for families after the battle.",
        },
      ],
    },
  ],
} as const satisfies ScenarioDefinition;

export const WATERLOO_WHAT_IF_PRESETS = [
  {
    id: "ground-dries-earlier",
    type: "weather",
    label: "Ground dries earlier",
    description: "Reduce the rain and mud penalty, allowing the field to become more passable sooner than it did historically.",
    source: "user",
    startsAtTick: 0,
    weather: { condition: "overcast", precipitation: 18, visibility: 76 },
  },
  {
    id: "prussian-arrival-delayed",
    type: "event",
    label: "Prussian vanguard is delayed",
    description: "Remove the modeled Prussian vanguard arrival, testing how much the Allied line depends on timely coalition support.",
    source: "user",
    startsAtTick: 0,
    eventId: "prussian-vanguard-arrives",
    mode: "disable",
  },
  {
    id: "allied-ammunition-resupplied",
    type: "resource",
    label: "Allied ammunition is resupplied",
    description: "Give the Allied and Prussian coalition an additional starting reserve of campaign supplies.",
    source: "user",
    startsAtTick: 0,
    factionId: "sun-liu",
    resource: "supplies",
    amount: 26,
  },
] as const satisfies readonly WhatIfModifier[];
